### ISSUE TITLE
Error at the Deploy step

### ISSUE THREAD

**Issue by vuhondat** [aws-samples/multidomain-spa-with-cdk-and-cloudfront#2]
Hi Paul Kukiel,

When I try to run Deploy cmd: [cdk deploy -c domainName=mydomain.com]

The error occured:
"[Error at /wildCardStaticApp] Found zones: [] for dns:exampledomain.com, privateZone:undefined, vpcId:undefined, but wanted exactly 1 zone
Found errors"

Kindly check and advice.

Thanks so much.
Vu Pham

**Comment by kukielp** [comment]
Hi Vu,

Can you confirm that you have a domain delegated to Route53 and that you are passing that domain name as the variable to the cdk deploy step?  There is a dependancy on a domain/zone in Route53

**Comment by vuhondat** [comment]
Hi Paul Kukiel,

I did. You can see:
![Screen Shot 2021-08-08 at 15 26 47](https://user-images.githubusercontent.com/12470007/128626031-e1123bfc-7972-4213-8d68-dce354323cd0.png)

Thanks,
Vu

**Comment by kukielp** [comment]
Hi Vu, 

There was a small typo, I have fixed this in the main branch, the cmd should be:

cdk deploy -c primaryDomain=mydomain.com

Thank you for reporting this.

**Comment by vuhondat** [comment]
Hi Paul Kukiel,

I've just tested. It's worked fine:
<img width="444" alt="Screen Shot 2021-08-09 at 09 53 32" src="https://user-images.githubusercontent.com/12470007/128655940-c0b1b87c-d133-474b-a4e1-bdc5f81d6182.png">

Thanks so much!

Regards,
Vu

**Comment by advissor** [comment]
@kukielp please also correct this typo in the Blog article

https://aws.amazon.com/blogs/infrastructure-and-automation/deploy-spa-with-personalized-subdomains-using-aws-cdk/

It uses old var name, so fails during deploy step 

`cdk deploy -c domainName=<your-domain.name>`

Thanks!
